nelmio_api_doc:
    documentation:
        info:
            title: TaskFlow Manager API
            description: API REST de gestion de projets et de tâches
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!(_profiler|_wdt|_error|api/doc))
